import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'ar' || saved === 'en') ? saved : 'ar';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      value = value?.[k];
    }

    return value || key;
  };

  const value = {
    language,
    setLanguage,
    t,
    isRTL: language === 'ar',
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

const translations: Record<Language, any> = {
  ar: {
    common: {
      welcome: 'مرحباً',
      loading: 'جاري التحميل...',
      save: 'حفظ',
      cancel: 'إلغاء',
      delete: 'حذف',
      edit: 'تعديل',
      add: 'إضافة',
      search: 'بحث',
      actions: 'الإجراءات',
      status: 'الحالة',
      active: 'نشط',
      inactive: 'غير نشط',
      yes: 'نعم',
      no: 'لا',
      logout: 'تسجيل خروج',
    },
    auth: {
      login: 'تسجيل الدخول',
      register: 'إنشاء حساب',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      fullName: 'الاسم الكامل',
      signIn: 'دخول',
      signUp: 'تسجيل',
      alreadyHaveAccount: 'لديك حساب؟',
      dontHaveAccount: 'ليس لديك حساب؟',
      loginTitle: 'نظام إدارة الحضور',
      loginSubtitle: 'سجل دخول للوصول إلى لوحة التحكم',
      registerTitle: 'إنشاء حساب جديد',
      registerSubtitle: 'املأ البيانات التالية لإنشاء حساب',
      loggingIn: 'جاري تسجيل الدخول...',
      registering: 'جاري التسجيل...',
    },
    nav: {
      dashboard: 'لوحة التحكم',
      employees: 'الموظفين',
      attendance: 'الحضور',
      branches: 'الفروع',
      shifts: 'الورديات',
      reports: 'التقارير',
      fraudAlerts: 'تنبيهات الاحتيال',
      settings: 'الإعدادات',
    },
    dashboard: {
      title: 'لوحة التحكم',
      totalEmployees: 'إجمالي الموظفين',
      presentToday: 'الحاضرون اليوم',
      absentToday: 'الغائبون اليوم',
      activeBranches: 'الفروع النشطة',
      recentActivity: 'النشاط الأخير',
      viewAll: 'عرض الكل',
      serverTime: 'وقت السيرفر الفعلي',
      attendanceTrends: 'اتجاهات الحضور',
      quickActions: 'إجراءات سريعة',
      onTimeRate: 'نسبة الحضور في الوقت',
      lateRate: 'نسبة التأخير',
      attendanceRate: 'نسبة الحضور',
      addNewEmployee: 'إضافة موظف جديد',
      addNewEmployeeDesc: 'تسجيل موظف جديد في النظام',
      addNewBranch: 'إضافة فرع جديد',
      addNewBranchDesc: 'إنشاء موقع عمل جديد مع تحديد الموقع الجغرافي',
      generateReport: 'إنشاء تقرير',
      generateReportDesc: 'تصدير بيانات الحضور والتحليلات',
      attendanceByBranch: 'الحضور حسب الفرع',
      branchName: 'اسم الفرع',
      presentEmployees: 'الموظفين الحاضرين',
      branchTotalEmployees: 'إجمالي الموظفين',
      attendancePercentage: 'نسبة الحضور',
      close: 'إغلاق',
      noData: 'لا توجد بيانات',
    },
    employees: {
      title: 'الموظفين',
      addEmployee: 'إضافة موظف',
      employeeId: 'رقم الموظف',
      name: 'الاسم',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      branch: 'الفرع',
      position: 'المسمى الوظيفي',
      department: 'القسم',
      status: 'الحالة',
      hireDate: 'تاريخ التعيين',
      noEmployees: 'لا يوجد موظفين',
    },
    attendance: {
      title: 'سجل الحضور',
      employee: 'الموظف',
      branch: 'الفرع',
      allBranches: 'جميع الفروع',
      date: 'التاريخ',
      checkIn: 'وقت الدخول',
      checkOut: 'وقت الخروج',
      status: 'الحالة',
      device: 'الجهاز',
      noRecords: 'لا توجد سجلات حضور',
      noRecordsDesc: 'لم يتم العثور على تسجيلات دخول للتاريخ المحدد',
      present: 'حاضر',
      absent: 'غائب',
      late: 'متأخر',
      onTime: 'في الوقت',
      earlyLeave: 'مغادرة مبكرة',
      pending: 'قيد الانتظار',
      totalRecords: 'إجمالي السجلات',
      lateArrivals: 'متأخرون',
      hours: 'ساعات',
      location: 'الموقع',
      viewMap: 'عرض الخريطة',
      monitorCheckIns: 'مراقبة تسجيلات الدخول والخروج للموظفين',
    },
    branches: {
      title: 'الفروع',
      addBranch: 'إضافة فرع',
      name: 'اسم الفرع',
      code: 'كود الفرع',
      address: 'العنوان',
      city: 'المدينة',
      manager: 'المدير',
      employeeCount: 'عدد الموظفين',
      noBranches: 'لا توجد فروع',
    },
    shifts: {
      title: 'الورديات',
      addShift: 'إضافة وردية',
      editShift: 'تعديل الوردية',
      deleteShift: 'حذف الوردية',
      shiftName: 'اسم الوردية',
      startTime: 'وقت البدء',
      endTime: 'وقت الانتهاء',
      noShifts: 'لا توجد ورديات',
      currentShift: 'الوردية الحالية',
      assignShift: 'تعيين وردية',
      shiftAssigned: 'الوردية المعينة',
      morningShift: 'الوردية الصباحية',
      eveningShift: 'الوردية المسائية',
      nightShift: 'الوردية الليلية',
      deleteConfirm: 'هل أنت متأكد من حذف هذه الوردية؟',
      shiftDeleted: 'تم حذف الوردية بنجاح',
      shiftAdded: 'تم إضافة الوردية بنجاح',
      shiftUpdated: 'تم تحديث الوردية بنجاح',
    },
    reports: {
      title: 'التقارير والتحليلات',
      subtitle: 'إنشاء وتصدير تقارير الحضور',
      generateReport: 'إنشاء تقرير',
      reportType: 'نوع التقرير',
      dateRange: 'الفترة الزمنية',
      attendance: 'تقرير الحضور',
      performance: 'تقرير الأداء',
      summary: 'تقرير ملخص',
      dailyReport: 'تقرير يومي',
      weeklyReport: 'تقرير أسبوعي',
      monthlyReport: 'تقرير شهري',
      customRange: 'فترة مخصصة',
      reportConfig: 'إعدادات التقرير',
      startDate: 'تاريخ البداية',
      endDate: 'تاريخ النهاية',
      reportFormat: 'صيغة التقرير',
      includeGPS: 'تضمين إحداثيات GPS',
      includeDevice: 'تضمين معلومات الجهاز',
      includeHours: 'تضمين تفاصيل ساعات العمل',
      includeLate: 'تضمين تفاصيل التأخير',
      previewReport: 'معاينة التقرير',
      downloadReport: 'تحميل التقرير',
      recentReports: 'التقارير الأخيرة',
      generatedOn: 'تم الإنشاء في',
      download: 'تحميل',
    },
    fraudAlerts: {
      title: 'كشف الاحتيال والتنبيهات',
      subtitle: 'مراقبة الأنشطة المشبوهة والتهديدات الأمنية',
      alertType: 'نوع التنبيه',
      severity: 'الخطورة',
      description: 'الوصف',
      timestamp: 'الوقت',
      resolved: 'تم الحل',
      pending: 'قيد المراجعة',
      all: 'الكل',
      unresolved: 'لم يتم الحل',
      high: 'عالية',
      medium: 'متوسطة',
      low: 'منخفضة',
      critical: 'حرجة',
      noAlerts: 'لم يتم العثور على تنبيهات',
      noAlertsDesc: 'النظام آمن دون تهديدات مكتشفة',
      totalAlerts: 'إجمالي التنبيهات',
      highPriority: 'أولوية عالية',
      fakeGPS: 'تم اكتشاف GPS وهمي',
      rootedDevice: 'جهاز مكسور الحماية',
      outOfRange: 'خارج السياج الجغرافي',
      poorGPSAccuracy: 'دقة GPS ضعيفة',
      timeManipulation: 'تلاعب بالوقت',
      suspiciousActivity: 'نشاط مشبوه',
      employee: 'الموظف',
      markResolved: 'وضع علامة تم الحل',
      viewDetails: 'عرض التفاصيل',
    },
    settings: {
      title: 'إعدادات النظام',
      subtitle: 'تكوين التفضيلات والسياسات على مستوى النظام',
      general: 'عام',
      security: 'الأمان',
      notifications: 'الإشعارات',
      system: 'النظام',
      language: 'اللغة',
      theme: 'المظهر',
      profile: 'الملف الشخصي',
      gpsSettings: 'إعدادات GPS',
      maxGPSAccuracy: 'أقصى دقة GPS (متر)',
      warningThreshold: 'عتبة التحذير (متر)',
      requireHighAccuracy: 'طلب وضع الدقة العالية',
      enableFakeGPSDetection: 'تفعيل كشف GPS الوهمي',
      attendanceRules: 'قواعد الحضور',
      gracePeriod: 'فترة السماح (دقيقة)',
      earlyCheckInAllowed: 'السماح بالدخول المبكر (دقيقة)',
      requireCheckOut: 'طلب تسجيل الخروج',
      blockDuplicateCheckIns: 'حظر تسجيلات الدخول المكررة',
      securityFraudDetection: 'الأمان وكشف الاحتيال',
      detectRootedDevices: 'كشف الأجهزة المكسورة الحماية',
      detectFakeGPS: 'كشف تطبيقات GPS الوهمية',
      detectTimeManipulation: 'كشف التلاعب بالوقت',
      blockSuspiciousDevices: 'حظر الأجهزة المشبوهة',
      maxDistanceJump: 'أقصى قفزة مسافة (متر)',
      notifyLateArrival: 'إشعار عند التأخير',
      notifyEarlyLeave: 'إشعار عند المغادرة المبكرة',
      notifyAbsence: 'إشعار عند الغياب',
      notifyFraudAlerts: 'إشعار عند تنبيهات الاحتيال',
      adminEmail: 'البريد الإلكتروني للمسؤول',
      otpConfiguration: 'إعدادات OTP',
      otpLength: 'طول OTP (أرقام)',
      expiryTime: 'وقت الانتهاء (دقيقة)',
      maxAttempts: 'الحد الأقصى للمحاولات',
      deliveryMethod: 'طريقة التسليم',
      sms: 'رسالة نصية',
      email: 'بريد إلكتروني',
      inApp: 'داخل التطبيق',
      regionalSettings: 'الإعدادات الإقليمية',
      defaultLanguage: 'اللغة الافتراضية',
      defaultTimezone: 'المنطقة الزمنية الافتراضية',
      dateFormat: 'تنسيق التاريخ',
      resetToDefaults: 'إعادة تعيين الإعدادات الافتراضية',
      saveChanges: 'حفظ التغييرات',
    },
  },
  en: {
    common: {
      welcome: 'Welcome',
      loading: 'Loading...',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search',
      actions: 'Actions',
      status: 'Status',
      active: 'Active',
      inactive: 'Inactive',
      yes: 'Yes',
      no: 'No',
      logout: 'Logout',
    },
    auth: {
      login: 'Login',
      register: 'Register',
      email: 'Email',
      password: 'Password',
      fullName: 'Full Name',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      alreadyHaveAccount: 'Already have an account?',
      dontHaveAccount: "Don't have an account?",
      loginTitle: 'Attendance Management System',
      loginSubtitle: 'Sign in to access your dashboard',
      registerTitle: 'Create New Account',
      registerSubtitle: 'Fill in the details to create an account',
      loggingIn: 'Logging in...',
      registering: 'Registering...',
    },
    nav: {
      dashboard: 'Dashboard',
      employees: 'Employees',
      attendance: 'Attendance',
      branches: 'Branches',
      shifts: 'Shifts',
      reports: 'Reports',
      fraudAlerts: 'Fraud Alerts',
      settings: 'Settings',
    },
    dashboard: {
      title: 'Dashboard',
      totalEmployees: 'Total Employees',
      presentToday: 'Present Today',
      absentToday: 'Absent Today',
      activeBranches: 'Active Branches',
      recentActivity: 'Recent Activity',
      viewAll: 'View All',
      serverTime: 'Live Server Time',
      attendanceTrends: 'Attendance Trends',
      quickActions: 'Quick Actions',
      onTimeRate: 'On-Time Rate',
      lateRate: 'Late Rate',
      attendanceRate: 'Attendance Rate',
      addNewEmployee: 'Add New Employee',
      addNewEmployeeDesc: 'Register a new employee in the system',
      addNewBranch: 'Add New Branch',
      addNewBranchDesc: 'Set up a new work location with geofence',
      generateReport: 'Generate Report',
      generateReportDesc: 'Export attendance data and analytics',
      attendanceByBranch: 'Attendance by Branch',
      branchName: 'Branch Name',
      presentEmployees: 'Present Employees',
      branchTotalEmployees: 'Total Employees',
      attendancePercentage: 'Attendance Rate',
      close: 'Close',
      noData: 'No data available',
    },
    employees: {
      title: 'Employees',
      addEmployee: 'Add Employee',
      employeeId: 'Employee ID',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      branch: 'Branch',
      position: 'Position',
      department: 'Department',
      status: 'Status',
      hireDate: 'Hire Date',
      noEmployees: 'No employees found',
    },
    attendance: {
      title: 'Attendance Log',
      employee: 'Employee',
      branch: 'Branch',
      allBranches: 'All Branches',
      date: 'Date',
      checkIn: 'Check In',
      checkOut: 'Check Out',
      status: 'Status',
      device: 'Device',
      noRecords: 'No attendance records',
      noRecordsDesc: 'No check-ins found for selected date',
      present: 'Present',
      absent: 'Absent',
      late: 'Late',
      onTime: 'On Time',
      earlyLeave: 'Early Leave',
      pending: 'Pending',
      totalRecords: 'Total Records',
      lateArrivals: 'Late Arrivals',
      hours: 'Hours',
      location: 'Location',
      viewMap: 'View Map',
      monitorCheckIns: 'Monitor employee check-ins and check-outs',
    },
    branches: {
      title: 'Branches',
      addBranch: 'Add Branch',
      name: 'Branch Name',
      code: 'Branch Code',
      address: 'Address',
      city: 'City',
      manager: 'Manager',
      employeeCount: 'Employee Count',
      noBranches: 'No branches found',
    },
    shifts: {
      title: 'Shifts',
      addShift: 'Add Shift',
      editShift: 'Edit Shift',
      deleteShift: 'Delete Shift',
      shiftName: 'Shift Name',
      startTime: 'Start Time',
      endTime: 'End Time',
      noShifts: 'No shifts found',
      currentShift: 'Current Shift',
      assignShift: 'Assign Shift',
      shiftAssigned: 'Shift Assigned',
      morningShift: 'Morning Shift',
      eveningShift: 'Evening Shift',
      nightShift: 'Night Shift',
      deleteConfirm: 'Are you sure you want to delete this shift?',
      shiftDeleted: 'Shift deleted successfully',
      shiftAdded: 'Shift added successfully',
      shiftUpdated: 'Shift updated successfully',
    },
    reports: {
      title: 'Reports & Analytics',
      subtitle: 'Generate and export attendance reports',
      generateReport: 'Generate Report',
      reportType: 'Report Type',
      dateRange: 'Date Range',
      attendance: 'Attendance Report',
      performance: 'Performance Report',
      summary: 'Summary Report',
      dailyReport: 'Daily Report',
      weeklyReport: 'Weekly Report',
      monthlyReport: 'Monthly Report',
      customRange: 'Custom Range',
      reportConfig: 'Report Configuration',
      startDate: 'Start Date',
      endDate: 'End Date',
      reportFormat: 'Report Format',
      includeGPS: 'Include GPS coordinates',
      includeDevice: 'Include device information',
      includeHours: 'Include working hours breakdown',
      includeLate: 'Include late arrival details',
      previewReport: 'Preview Report',
      downloadReport: 'Download Report',
      recentReports: 'Recent Reports',
      generatedOn: 'Generated on',
      download: 'Download',
    },
    fraudAlerts: {
      title: 'Fraud Detection & Alerts',
      subtitle: 'Monitor suspicious activities and security threats',
      alertType: 'Alert Type',
      severity: 'Severity',
      description: 'Description',
      timestamp: 'Timestamp',
      resolved: 'Resolved',
      pending: 'Pending',
      all: 'All',
      unresolved: 'Unresolved',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      critical: 'Critical',
      noAlerts: 'No alerts found',
      noAlertsDesc: 'System is secure with no detected threats',
      totalAlerts: 'Total Alerts',
      highPriority: 'High Priority',
      fakeGPS: 'Fake GPS Detected',
      rootedDevice: 'Rooted/Jailbroken Device',
      outOfRange: 'Outside Geofence',
      poorGPSAccuracy: 'Poor GPS Accuracy',
      timeManipulation: 'Time Manipulation',
      suspiciousActivity: 'Suspicious Activity',
      employee: 'Employee',
      markResolved: 'Mark as Resolved',
      viewDetails: 'View Details',
    },
    settings: {
      title: 'System Settings',
      subtitle: 'Configure system-wide preferences and policies',
      general: 'General',
      security: 'Security',
      notifications: 'Notifications',
      system: 'System',
      language: 'Language',
      theme: 'Theme',
      profile: 'Profile',
      gpsSettings: 'GPS Settings',
      maxGPSAccuracy: 'Maximum GPS Accuracy (meters)',
      warningThreshold: 'Warning Threshold (meters)',
      requireHighAccuracy: 'Require high accuracy mode',
      enableFakeGPSDetection: 'Enable fake GPS detection',
      attendanceRules: 'Attendance Rules',
      gracePeriod: 'Grace Period (minutes)',
      earlyCheckInAllowed: 'Early Check-in Allowed (minutes)',
      requireCheckOut: 'Require check-out',
      blockDuplicateCheckIns: 'Block duplicate check-ins',
      securityFraudDetection: 'Security & Fraud Detection',
      detectRootedDevices: 'Detect rooted/jailbroken devices',
      detectFakeGPS: 'Detect fake GPS apps',
      detectTimeManipulation: 'Detect time manipulation',
      blockSuspiciousDevices: 'Block suspicious devices',
      maxDistanceJump: 'Max Distance Jump (meters)',
      notifyLateArrival: 'Notify on late arrival',
      notifyEarlyLeave: 'Notify on early leave',
      notifyAbsence: 'Notify on absence',
      notifyFraudAlerts: 'Notify on fraud alerts',
      adminEmail: 'Admin Email',
      otpConfiguration: 'OTP Configuration',
      otpLength: 'OTP Length (digits)',
      expiryTime: 'Expiry Time (minutes)',
      maxAttempts: 'Maximum Attempts',
      deliveryMethod: 'Delivery Method',
      sms: 'SMS',
      email: 'Email',
      inApp: 'In-App',
      regionalSettings: 'Regional Settings',
      defaultLanguage: 'Default Language',
      defaultTimezone: 'Default Timezone',
      dateFormat: 'Date Format',
      resetToDefaults: 'Reset to Defaults',
      saveChanges: 'Save Changes',
    },
  },
};
